### ISSUE TITLE
Setup Continuous integration

### ISSUE THREAD

**Issue by srv-twry** [srv-twry/My-Companion#5]
Setup Continuous integration with either ```CircleCI``` or ```Travis CI``` , preferrably the earlier one.

**Comment by pjbollinger** [comment]
If you don't mind, I would like to try and set this up.

**Comment by srv-twry** [comment]
@pjbollinger Sure , please go ahead :smile:

**Comment by Cosmopal** [comment]
Account to be used? yours?

**Comment by srv-twry** [comment]
@Cosmopal Yup mine, I would just like to have the ```circle.yml``` created.

**Comment by pjbollinger** [comment]
Any specific branch you want this to be based off of? I plan on branching off of `development` since this really isn't a new feature to the app itself.

**Comment by srv-twry** [comment]
@pjbollinger Yeah you can branch it off from the ```development```.

**Comment by pjbollinger** [comment]
This setup (#6) will build all branches for the project. I think you need to setup the CircleCI project before accepting this pull request because it is triggered by changes to the repository, so you can see how it works. The build file is agnostic to the repo, but the README file is specific to this project/repository. Hope that helps!
